// showcase/vue-vite/src/containers/StoryFeed/StoryFeed.vue
<script setup lang="ts">
import { StoryCard } from '~app/components/StoryCard';
import { provideTheme } from '~app/contexts/themeContext';
import { useStories } from '~app/composables/useStories';

defineProps<{ limit: number }>();
provideTheme();
const stories = useStories();
</script>

<template>
  <StoryCard v-for="story in stories" :key="story.id" :story="story" />
</template>

// showcase/next-app-router/src/containers/StoryFeed.tsx
import { StoryCard } from '~app/components/StoryCard';
import { ThemeProvider } from '~app/contexts/ThemeContext';
import { useStories } from '~app/hooks/useStories';

export function StoryFeed({ limit }: { limit: number }) {
  const stories = useStories(limit);
  return <ThemeProvider>{stories.map((s) => <StoryCard key={s.id} story={s} />)}</ThemeProvider>;
}
